name: FirePlugin
version: 1.0
main: fr.fireplugin.NoixDeCoco
api-version: 1.20
commands:
  coco:
    description: Noix de coco
  pioche:
    description: Pioche 3x3
  craft:
    description: ouvre une  table de craft
  furnace:
    description: fait cuire les minerais automatiquement

permissions:
  FirePlugin.use:
    description: Utilise la commande /craft
    default: false
